CREATE DATABASE Tipography
USE Tipography

CREATE TABLE register(
id_user INT IDENTITY (1,1) NOT NULL,
login_user NVARCHAR(50) NOT NULL,
password_user NVARCHAR(50) NOT NULL,
is_admin TINYINT
);
DROP TABLE register
CREATE TABLE Client(
id_Client INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
Fio NVARCHAR(100) NOT NULL,
Phone VARCHAR(18) NOT NULL,
Address_c NVARCHAR(50) NOT NULL,
Organization NVARCHAR(30) NOT NULL
);

CREATE TABLE Employee(
id_Employee INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
Fio NVARCHAR(100) NOT NULL,
Age INT NOT NULL,
Job_title NVARCHAR(20) NOT NULL,
Phone VARCHAR(18) NOT NULL,
Salary VARCHAR(10) NOT NULL
);

CREATE TABLE Stock(
id_stock INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
Name NVARCHAR(20) NOT NULL,
Amount INT NOT NULL
);

CREATE TABLE Service(
id_Service INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
Name NVARCHAR(20) NOT NULL,
Cost VARCHAR(10) NOT NULL,
Material INT NOT NULL
FOREIGN KEY (Material) REFERENCES Stock(id_stock),
);

CREATE TABLE Orders(
id_Order INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
Client INT NOT NULL
FOREIGN KEY (Client) REFERENCES Client(id_Client),
Employee INT NOT NULL
FOREIGN KEY (Employee) REFERENCES Employee(id_Employee),
Service INT NOT NULL
FOREIGN KEY (Service) REFERENCES Service(id_Service),
Date SMALLDATETIME NOT NULL,
Amount_service INT NOT NULL,
Status NVARCHAR(11) NOT NULL,
Stock INT NOT NULL
FOREIGN KEY (Stock) REFERENCES Stock(id_stock)
);